// Code generated by mockery v2.14.0. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// IHashService is an autogenerated mock type for the IHashService type
type IHashService struct {
	mock.Mock
}

// HashString provides a mock function with given fields: s
func (_m *IHashService) HashString(s string) string {
	ret := _m.Called(s)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIHashService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIHashService creates a new instance of IHashService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHashService(t mockConstructorTestingTNewIHashService) *IHashService {
	mock := &IHashService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
